services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile             #Define the Dockerfile for the backend service
    container_name: tontine-backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - tontine-network

  frontend:
    build:
      context: ./frontend               
      dockerfile: Dockerfile            #Define the Dockerfile for the frontend service
    container_name: tontine-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - tontine-network

  mongo:
    image: mongo:latest
    container_name: tontine-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - tontine-network

volumes:
  mongo_data:

networks:
  tontine-network:
    driver: bridge
