- name: Deploy Tontine App to Production
  hosts: webserver
  become: true
  vars:
    acr_login_server: "{{ acr_login_server }}"
    acr_username: "{{ acr_username }}"
    acr_password: "{{ acr_password }}"
    image_tag: "{{ image_tag }}"
    mongo_uri: "{{ mongo_uri }}"
    jwt_secret: "{{ jwt_secret }}"
    backend_image: "{{ acr_login_server }}/tontine-backend:{{ image_tag }}"
    frontend_image: "{{ acr_login_server }}/tontine-frontend:{{ image_tag }}"  

  tasks:
    - name: Log into Azure Container Registry
      community.docker.docker_login:
        registry_url: "{{ acr_login_server }}"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"
        reauthorize: yes

    - name: Pull the backend Image
      community.docker.docker_image:
        name: "{{ acr_login_server }}/tontine-backend"
        tag: "{{ image_tag }}"
        source: pull
        force_source: yes

    - name: Stop and Remove Existing Container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: Run backend Container
      community.docker.docker_container:
        name: "tontine-backend"
        image: "{{ backend_image }}"
        state: started
        restart_policy: always
        ports:
          - "4000:4000"
        env:
          PORT: "4000"
          MONGO_URI: "{{ mongo_uri }}"
          JWT_SECRET: "{{ jwt_secret }}"
          NODE_ENV: "production"

    - name: Pull Frontend Image
      community.docker.docker_image:
        name: "{{ acr_login_server }}/tontine-frontend"
        tag: "{{ image_tag }}"
        source: pull
        force_source: yes

    - name: Run Frontend Container
      community.docker.docker_container:
        name: "tontine-frontend"
        image: "{{ frontend_image }}"
        state: started
        restart_policy: always
        recreate: yes
        ports:
          - "3000:80"